name: Build + Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  BASE_DEV_VERSION: 2.5.0

jobs:

  release:
    name: Publish Release Images
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Set Version Variables
      run: |
        echo "Using TAG mode: $GITHUB_REF_NAME"
        echo "REL_VERSION_STRICT=${GITHUB_REF_NAME#?}" >> $GITHUB_ENV

    - name: Parse REL_VERSION_STRICT
      uses: madhead/semver-utils@latest
      id: version
      with:
        version: ${ env.REL_VERSION_STRICT }

    - name: Debug semver
      run: |
        MAJOR=${{ steps.version.outputs.major }}
        MINOR=${{ steps.version.outputs.minor }}
        MAJORMINOR="$MAJOR.$MINOR"

        echo "Using major $MAJOR and minor $MINOR... ($MAJORMINOR)"
